local c = require('horizon.custom')

---@class horizon.Opts
---@field fg string
---@field bg string
---@field sp string
---@field bold boolean
---@field italic boolean
---@field underline boolean
---@field undercurl boolean
---@field reverse boolean
---@field standout boolean
---@field link string

---@alias horizon.HighlightDef {[string]: horizon.Opts}
---@alias Theme 'light' | 'dark'

local api = vim.api

local M = {}

---@param theme horizon.HighlightDef
local function get_lsp_kind_highlights(theme, custom)
  return {
    -- LSP Kind Items
    ['module'] = { fg = custom.yelloworange },
    ['snippet'] = { fg = custom.purple },
    ['folder'] = { fg = theme.fg },
    ['color'] = { fg = theme.fg },
    ['file'] = { link = 'Directory' },
    ['text'] = { link = '@string' },
    ['method'] = { link = '@method' },
    ['function'] = { link = '@function' },
    ['constructor'] = { link = '@constructor' },
    ['field'] = { link = '@field' },
    ['variable'] = { link = '@variable' },
    ['property'] = { link = '@property' },
    ['unit'] = { link = '@constant' },
    ['value'] = { link = '@variable' },
    ['enum'] = { link = '@type' },
    ['keyword'] = { link = '@keyword' },
    ['reference'] = { link = '@parameter.reference' },
    ['constant'] = { link = '@constant' },
    ['struct'] = { link = '@structure' },
    ['event'] = { link = '@variable' },
    ['operator'] = { link = '@operator' },
    ['namespace'] = { link = '@namespace' },
    ['package'] = { link = '@include' },
    ['string'] = { link = '@string' },
    ['number'] = { link = '@number' },
    ['boolean'] = { link = '@boolean' },
    ['array'] = { link = '@repeat' },
    ['object'] = { link = '@type' },
    ['key'] = { link = '@field' },
    ['null'] = { link = '@symbol' },
    ['enumMember'] = { link = '@field' },
    ['class'] = { link = '@lsp.type.class' },
    ['interface'] = { link = '@lsp.type.interface' },
    ['typeParameter'] = { link = '@lsp.type.parameter' },
  }
end

---@param bg Theme
---@return horizon.HighlightDef
local function get_highlights(bg)
  local custom = c[bg]
  ---@module 'horizon.palette-dark'
  local theme = require(('horizon.palette-%s'):format(bg))
  return {
    -- Editor
    ['Normal'] = { fg = theme.fg, bg = theme.bg },
    ['NormalNC'] = { fg = theme.fg, bg = theme.bg },
    ['SignColumn'] = {},
    ['MsgArea'] = { fg = theme.fg, bg = theme.bg },
    ['ModeMsg'] = { fg = theme.fg, bg = custom.alt_bg },
    ['MsgSeparator'] = { fg = theme.winseparator_fg, bg = theme.bg },
    ['SpellBad'] = { sp = custom.red, undercurl = true },
    ['SpellCap'] = { sp = custom.yellow, undercurl = true },
    ['SpellLocal'] = { sp = custom.yelloworange, underline = true },
    ['SpellRare'] = { sp = custom.purple, underline = true },
    ['Pmenu'] = { fg = theme.fg, bg = theme.pmenu_bg },
    ['PmenuSel'] = { bg = custom.ui2_blue },
    ['PmenuSbar'] = { bg = theme.pmenu_thumb_bg },
    ['PmenuThumb'] = { bg = theme.pmenu_thumb_fg },
    ['WildMenu'] = { fg = theme.fg, bg = custom.ui2_blue },
    ['CursorLineNr'] = { fg = theme.active_line_number_fg, bold = true },
    ['Folded'] = { fg = custom.gray, bg = custom.alt_bg },
    ['FoldColumn'] = { fg = custom.gray, bg = custom.alt_bg },
    ['LineNr'] = { fg = theme.inactive_line_number_fg },
    ['NormalFloat'] = { bg = theme.float_bg },
    ['FloatBorder'] = { fg = theme.float_border, bg = theme.float_bg },
    ['Whitespace'] = { fg = custom.pale_gray },
    ['VertSplit'] = { fg = theme.winseparator_fg, bg = theme.bg },
    ['CursorLine'] = { bg = theme.cursorline_bg },
    ['CursorColumn'] = { bg = custom.alt_bg },
    ['ColorColumn'] = { bg = custom.alt_bg },
    ['Visual'] = { bg = custom.ui_blue },
    ['VisualNOS'] = { bg = custom.alt_bg },
    ['WarningMsg'] = { fg = custom.error, bg = theme.bg },
    ['DiffAdd'] = { bg = theme.diff_added_bg },
    ['DiffDelete'] = { bg = theme.diff_deleted_bg },
    ['DiffChange'] = { bg = custom.diff_change },
    ['DiffText'] = { bg = custom.diff_text },
    ['QuickFixLine'] = { bg = custom.ui2_blue },
    ['MatchParen'] = { fg = theme.match_paren, underline = true },
    ['Cursor'] = { fg = theme.cursor_fg, bg = theme.cursor_bg },
    ['lCursor'] = { fg = theme.cursor_fg, bg = theme.cursor_bg },
    ['CursorIM'] = { fg = theme.cursor_fg, bg = theme.cursor_bg },
    ['TermCursor'] = { fg = theme.term_cursor_fg, bg = theme.term_cursor_bg },
    ['TermCursorNC'] = { fg = theme.term_cursor_fg, bg = theme.term_cursor_bg },
    ['Conceal'] = { fg = custom.gray },
    ['Directory'] = { fg = custom.blue },
    ['SpecialKey'] = { fg = custom.red, bold = true },
    ['ErrorMsg'] = { fg = custom.error, bg = theme.bg, bold = true },
    ['Search'] = { bg = custom.ui2_blue },
    ['IncSearch'] = { bg = custom.ui2_blue },
    ['Substitute'] = { bg = custom.ui2_blue },
    ['MoreMsg'] = { fg = custom.orange },
    ['Question'] = { fg = custom.orange },
    ['EndOfBuffer'] = { fg = theme.bg },
    ['NonText'] = { fg = theme.bg },
    ['TabLine'] = { fg = custom.light_gray, bg = custom.alt_bg },
    ['TabLineSel'] = { fg = theme.fg, bg = custom.alt_bg },
    ['TabLineFill'] = { fg = custom.alt_bg, bg = custom.alt_bg },

    -- Code
    ['Comment'] = theme.comment,
    ['Variable'] = { fg = custom.red },
    ['String'] = theme.string,
    ['Character'] = { fg = custom.yelloworange },
    ['Number'] = { fg = custom.orange },
    ['Float'] = { fg = custom.orange },
    ['Boolean'] = { fg = custom.orange },
    ['Constant'] = theme.constant,
    ['Type'] = { fg = custom.yellow },
    ['Function'] = theme.func,
    ['Keyword'] = theme.keyword,
    ['Conditional'] = { fg = custom.purple },
    ['Repeat'] = { fg = custom.purple },
    ['Operator'] = { link = 'Delimiter' },
    ['PreProc'] = { fg = custom.purple },
    ['Include'] = { fg = custom.purple },
    ['Exception'] = { fg = custom.purple },
    ['StorageClass'] = { fg = custom.yellow },
    ['Structure'] = { fg = custom.yellow },
    ['Typedef'] = { fg = custom.purple },
    ['Define'] = { fg = custom.purple },
    ['Macro'] = { fg = custom.purple },
    ['Debug'] = { fg = custom.red },
    ['Title'] = { fg = custom.yellow, bold = true },
    ['Label'] = { fg = custom.red },
    ['SpecialChar'] = { fg = custom.yelloworange },
    ['Delimiter'] = theme.delimiter,
    ['SpecialComment'] = { fg = theme.fg },
    ['Tag'] = { fg = custom.red },
    ['Bold'] = { bold = true },
    ['Italic'] = { italic = true },
    ['Underlined'] = { underline = true },
    ['Ignore'] = { fg = custom.hint, bold = true },
    ['Todo'] = { fg = custom.info, bold = true },
    ['Error'] = { fg = custom.error, bold = true },
    ['Statement'] = { fg = custom.purple },
    ['Identifier'] = { fg = theme.fg },
    ['PreCondit'] = { fg = custom.purple },
    ['Special'] = { fg = custom.orange },

    -- Treesitter
    ['@comment'] = { link = 'Comment' },
    ['@variable'] = { link = 'Variable' },
    ['@string'] = { link = 'String' },
    ['@string.regex'] = { link = 'String' },
    ['@string.escape'] = { link = 'String' },
    ['@character'] = { link = 'String' },
    ['@character.special'] = { link = 'SpecialChar' },
    ['@number'] = { link = 'Number' },
    ['@float'] = { link = 'Float' },
    ['@boolean'] = { link = 'Boolean' },
    ['@constant'] = { link = 'Constant' },
    ['@constant.builtin'] = { link = 'Constant' },
    ['@constructor'] = { link = 'Type' },
    ['@type'] = { link = 'Type' },
    ['@include'] = { link = 'Include' },
    ['@exception'] = { link = 'Exception' },
    ['@keyword'] = { link = 'Keyword' },
    ['@keyword.return'] = { link = 'Keyword' },
    ['@keyword.operator'] = { link = 'Keyword' },
    ['@keyword.function'] = { link = 'Keyword' },
    ['@function'] = { link = 'Function' },
    ['@function.builtin'] = { link = 'Function' },
    ['@method'] = { link = 'Function' },
    ['@function.macro'] = { link = 'Function' },
    ['@conditional'] = { link = 'Conditional' },
    ['@repeat'] = { link = 'Repeat' },
    ['@operator'] = { link = 'Operator' },
    ['@preproc'] = { link = 'PreProc' },
    ['@storageclass'] = { link = 'StorageClass' },
    ['@structure'] = { link = 'Structure' },
    ['@type.definition'] = { link = 'Typedef' },
    ['@define'] = { link = 'Define' },
    ['@note'] = { link = 'Comment' },
    ['@none'] = { fg = custom.light_gray },
    ['@todo'] = { link = 'Todo' },
    ['@debug'] = { link = 'Debug' },
    ['@danger'] = { link = 'Error' },
    ['@title'] = { link = 'Title' },
    ['@label'] = { link = 'Label' },
    ['@tag.delimiter'] = { fg = custom.red },
    ['@punctuation.delimiter'] = { link = 'Delimiter' },
    ['@punctuation.bracket'] = { link = 'Delimiter' },
    ['@punctuation.special'] = { link = 'Delimiter' },
    ['@tag'] = { link = 'Tag' },
    ['@strong'] = { link = 'Bold' },
    ['@emphasis'] = { link = 'Italic' },
    ['@underline'] = { link = 'Underline' },
    ['@strike'] = { strikethrough = true },
    ['@string.special'] = { fg = theme.fg },
    ['@environment.name'] = { fg = custom.cyan },
    ['@variable.builtin'] = { fg = custom.yellow },
    ['@const.macro'] = { fg = custom.orange },
    ['@type.builtin'] = { fg = custom.orange },
    ['@annotation'] = { fg = custom.cyan },
    ['@namespace'] = { fg = custom.cyan },
    ['@symbol'] = { fg = theme.fg },
    ['@field'] = { fg = custom.red },
    ['@property'] = { fg = custom.red },
    ['@parameter'] = { fg = custom.red },
    ['@parameter.reference'] = theme.parameter,
    ['@attribute'] = { fg = custom.red },
    ['@text'] = { fg = custom.light_gray },
    ['@text.reference'] = { fg = theme.link.fg, sp = custom.reference, underline = true, bold = true },
    ['@tag.attribute'] = { fg = custom.orange, italic = true },
    ['@error'] = { fg = theme.error },
    ['@warning'] = { fg = theme.warning },
    ['@query.linter.error'] = { fg = custom.error },
    ['@uri'] = { fg = custom.cyan, underline = true },
    ['@math'] = { fg = custom.yellow },

    -- LspSemanticTokens
    ['@lsp.type.namespace'] = { link = '@namespace' },
    ['@lsp.type.type'] = { link = '@type' },
    ['@lsp.type.class'] = { link = '@type' },
    ['@lsp.type.enum'] = { link = '@type' },
    ['@lsp.type.interface'] = { link = '@type' },
    ['@lsp.type.struct'] = { link = '@structure' },
    ['@lsp.type.typeParameter'] = { link = 'TypeDef' },
    ['@lsp.type.variable'] = { link = '@variable' },
    ['@lsp.type.property'] = { link = '@property' },
    ['@lsp.type.enumMember'] = { link = '@constant' },
    ['@lsp.type.function'] = { link = '@function' },
    ['@lsp.type.method'] = { link = '@method' },
    ['@lsp.type.macro'] = { link = '@macro' },
    ['@lsp.type.decorator'] = { link = '@function' },
    ['@lsp.typemod.variable.readonly'] = { link = '@constant' },
    ['@lsp.typemod.method.defaultLibrary'] = { link = '@function.builtin' },
    ['@lsp.typemod.function.defaultLibrary'] = { link = '@function.builtin' },
    ['@lsp.typemod.variable.defaultLibrary'] = { link = '@variable.builtin' },
    ['@lsp.mod.deprecated'] = { strikethrough = true },

    -- LSP
    ['DiagnosticHint'] = { fg = custom.hint },
    ['DiagnosticInfo'] = { fg = custom.info },
    ['DiagnosticWarn'] = { fg = custom.warn },
    ['DiagnosticError'] = { fg = custom.error },
    ['DiagnosticOther'] = { fg = custom.ui_purple },
    ['DiagnosticSignHint'] = { link = 'DiagnosticHint' },
    ['DiagnosticSignInfo'] = { link = 'DiagnosticInfo' },
    ['DiagnosticSignWarn'] = { link = 'DiagnosticWarn' },
    ['DiagnosticSignError'] = { link = 'DiagnosticError' },
    ['DiagnosticSignOther'] = { link = 'DiagnosticOther' },
    ['DiagnosticSignWarning'] = { link = 'DiagnosticWarn' },
    ['DiagnosticFloatingHint'] = { link = 'DiagnosticHint' },
    ['DiagnosticFloatingInfo'] = { link = 'DiagnosticInfo' },
    ['DiagnosticFloatingWarn'] = { link = 'DiagnosticWarn' },
    ['DiagnosticFloatingError'] = { link = 'DiagnosticError' },
    ['DiagnosticUnderlineHint'] = { sp = custom.hint, undercurl = true },
    ['DiagnosticUnderlineInfo'] = { sp = custom.info, undercurl = true },
    ['DiagnosticUnderlineWarn'] = { sp = custom.warn, undercurl = true },
    ['DiagnosticUnderlineError'] = { sp = custom.error, undercurl = true },
    ['DiagnosticSignInformation'] = { link = 'DiagnosticInfo' },
    ['DiagnosticVirtualTextHint'] = { fg = custom.hint, bg = custom.hint_bg },
    ['DiagnosticVirtualTextInfo'] = { fg = custom.info, bg = custom.info_bg },
    ['DiagnosticVirtualTextWarn'] = { fg = custom.warn, bg = custom.warn_bg },
    ['DiagnosticVirtualTextError'] = { fg = custom.error, bg = custom.error_bg },
    ['LspDiagnosticsError'] = { fg = custom.error },
    ['LspDiagnosticsWarning'] = { fg = custom.warn },
    ['LspDiagnosticsInfo'] = { fg = custom.info },
    ['LspDiagnosticsInformation'] = { link = 'LspDiagnosticsInfo' },
    ['LspDiagnosticsHint'] = { fg = custom.hint },
    ['LspDiagnosticsDefaultError'] = { link = 'LspDiagnosticsError' },
    ['LspDiagnosticsDefaultWarning'] = { link = 'LspDiagnosticsWarning' },
    ['LspDiagnosticsDefaultInformation'] = { link = 'LspDiagnosticsInfo' },
    ['LspDiagnosticsDefaultInfo'] = { link = 'LspDiagnosticsInfo' },
    ['LspDiagnosticsDefaultHint'] = { link = 'LspDiagnosticsHint' },
    ['LspDiagnosticsVirtualTextError'] = { link = 'DiagnosticVirtualTextError' },
    ['LspDiagnosticsVirtualTextWarning'] = { link = 'DiagnosticVirtualTextWarn' },
    ['LspDiagnosticsVirtualTextInformation'] = { link = 'DiagnosticVirtualTextInfo' },
    ['LspDiagnosticsVirtualTextInfo'] = { link = 'DiagnosticVirtualTextInfo' },
    ['LspDiagnosticsVirtualTextHint'] = { link = 'DiagnosticVirtualTextHint' },
    ['LspDiagnosticsFloatingError'] = { link = 'LspDiagnosticsError' },
    ['LspDiagnosticsFloatingWarning'] = { link = 'LspDiagnosticsWarning' },
    ['LspDiagnosticsFloatingInformation'] = { link = 'LspDiagnosticsInfo' },
    ['LspDiagnosticsFloatingInfo'] = { link = 'LspDiagnosticsInfo' },
    ['LspDiagnosticsFloatingHint'] = { link = 'LspDiagnosticsHint' },
    ['LspDiagnosticsSignError'] = { link = 'LspDiagnosticsError' },
    ['LspDiagnosticsSignWarning'] = { link = 'LspDiagnosticsWarning' },
    ['LspDiagnosticsSignInformation'] = { link = 'LspDiagnosticsInfo' },
    ['LspDiagnosticsSignInfo'] = { link = 'LspDiagnosticsInfo' },
    ['LspDiagnosticsSignHint'] = { link = 'LspDiagnosticsHint' },
    ['NvimTreeLspDiagnosticsError'] = { link = 'LspDiagnosticsError' },
    ['NvimTreeLspDiagnosticsWarning'] = { link = 'LspDiagnosticsWarning' },
    ['NvimTreeLspDiagnosticsInformation'] = { link = 'LspDiagnosticsInfo' },
    ['NvimTreeLspDiagnosticsInfo'] = { link = 'LspDiagnosticsInfo' },
    ['NvimTreeLspDiagnosticsHint'] = { link = 'LspDiagnosticsHint' },
    ['LspDiagnosticsUnderlineError'] = { link = 'DiagnosticUnderlineError' },
    ['LspDiagnosticsUnderlineWarning'] = { link = 'DiagnosticUnderlineWarn' },
    ['LspDiagnosticsUnderlineInformation'] = { link = 'DiagnosticUnderlineInfo' },
    ['LspDiagnosticsUnderlineInfo'] = { link = 'DiagnosticUnderlineInfo' },
    ['LspDiagnosticsUnderlineHint'] = { link = 'DiagnosticUnderlineHint' },
    ['LspReferenceRead'] = { bg = custom.reference },
    ['LspReferenceText'] = { bg = custom.reference },
    ['LspReferenceWrite'] = { bg = custom.reference },
    ['LspCodeLens'] = { fg = theme.codelens_fg, italic = true },
    ['LspCodeLensSeparator'] = { fg = theme.codelens_fg, italic = true },

    -- StatusLine
    ['StatusLine'] = { fg = theme.statusline_fg, bg = theme.statusline_bg },
    ['StatusLineNC'] = { fg = custom.alt_bg, bg = theme.statusline_bg },
    ['StatusLineSeparator'] = { fg = theme.statusline_bg },
    ['StatusLineTerm'] = { fg = theme.statusline_bg },
    ['StatusLineTermNC'] = { fg = theme.statusline_bg },
  }
end

---@param bg Theme
---@return horizon.HighlightDef
local function get_plugin_highlights(bg)
  local custom = c[bg]
  ---@module 'horizon.palette-dark'
  local theme = require(('horizon.palette-%s'):format(bg))
  local lsp_kinds = get_lsp_kind_highlights(theme, custom)
  return {
    whichkey = {
      ['WhichKey'] = { fg = custom.purple },
      ['WhichKeySeperator'] = { fg = custom.yellow },
      ['WhichKeyGroup'] = { fg = custom.red },
      ['WhichKeyDesc'] = { fg = theme.fg },
      ['WhichKeyFloat'] = { bg = custom.alt_bg },
    },
    gitsigns = {
      ['SignAdd'] = { fg = theme.git_added_fg },
      ['SignChange'] = { fg = theme.git_modified_fg },
      ['SignDelete'] = { fg = theme.git_deleted_fg },
      ['GitSignsAdd'] = { fg = theme.git_added_fg },
      ['GitSignsChange'] = { fg = theme.git_modified_fg },
      ['GitSignsDelete'] = { fg = theme.git_deleted_fg },
      ['GitSignsUntracked'] = { fg = theme.git_untracked_fg },
      ['GitSignsAddInline'] = { link = 'DiffText' },
    },
    quickscope = {
      ['QuickScopePrimary'] = { fg = '#ff007c', underline = true },
      ['QuickScopeSecondary'] = { fg = '#00dfff', underline = true },
    },
    telescope = {
      ['TelescopeSelection'] = { bg = custom.ui2_blue },
      ['TelescopeSelectionCaret'] = { fg = custom.red, bg = custom.ui2_blue },
      ['TelescopeMatching'] = { fg = custom.yellow, bold = true, italic = true },
      ['TelescopeBorder'] = { fg = custom.alt_fg },
      ['TelescopeNormal'] = { fg = custom.light_gray, bg = custom.alt_bg },
      ['TelescopePromptTitle'] = { fg = custom.orange },
      ['TelescopePromptPrefix'] = { fg = custom.cyan },
      ['TelescopeResultsTitle'] = { fg = custom.orange },
      ['TelescopePreviewTitle'] = { fg = custom.orange },
      ['TelescopePromptCounter'] = { fg = custom.red },
      ['TelescopePreviewHyphen'] = { fg = custom.red },
    },
    nvim_tree = {
      ['NvimTreeFolderIcon'] = { fg = custom.gold },
      ['NvimTreeIndentMarker'] = { fg = custom.gray },
      ['NvimTreeNormal'] = { fg = theme.sidebar_fg, bg = theme.sidebar_bg },
      ['NvimTreeVertSplit'] = { fg = theme.sidebar_bg, bg = theme.sidebar_bg },
      ['NvimTreeFolderName'] = { fg = theme.sidebar_fg },
      ['NvimTreeOpenedFolderName'] = { fg = theme.sidebar_fg, bold = true, italic = true },
      ['NvimTreeEmptyFolderName'] = theme.comment,
      ['NvimTreeGitIgnored'] = theme.comment,
      ['NvimTreeImageFile'] = { fg = custom.light_gray },
      ['NvimTreeSpecialFile'] = { fg = custom.orange },
      ['NvimTreeEndOfBuffer'] = { fg = theme.comment.fg },
      ['NvimTreeCursorLine'] = { bg = theme.cursorline_bg },
      ['NvimTreeGitStaged'] = { fg = theme.git_added_fg },
      ['NvimTreeGitNew'] = { fg = theme.git_untracked_fg },
      ['NvimTreeGitRenamed'] = { fg = theme.git_modified_fg },
      ['NvimTreeGitDeleted'] = { fg = theme.git_deleted_fg },
      ['NvimTreeGitMerge'] = { fg = theme.git_modified_fg },
      ['NvimTreeGitDirty'] = { fg = theme.git_untracked_fg },
      ['NvimTreeSymlink'] = { fg = custom.cyan },
      ['NvimTreeRootFolder'] = { fg = theme.fg, bold = true },
      ['NvimTreeExecFile'] = { fg = '#9FBA89' },
    },
    neo_tree = {
      ['NeoTreeFolderIcon'] = { fg = custom.gold },
      ['NeoTreeIndentMarker'] = { fg = custom.gray },
      ['NeoTreeNormal'] = { fg = theme.sidebar_fg, bg = theme.sidebar_bg },
      ['NeoTreeFileName'] = { fg = theme.fg },
      ['NeoTreeDirectoryName'] = { fg = theme.sidebar_fg },
      ['NeoTreeDirectoryIcon'] = { fg = custom.gold },
      ['NeoTreeVertSplit'] = { fg = theme.sidebar_bg, bg = theme.sidebar_bg },
      ['NeoTreeWinSeparator'] = { fg = theme.sidebar_bg, bg = theme.sidebar_bg },
      ['NeoTreeOpenedFolderName'] = { fg = theme.fg, bold = true, italic = true },
      ['NeoTreeEmptyFolderName'] = { fg = theme.comment.fg, italic = true },
      ['NeoTreeGitIgnored'] = { fg = theme.comment.fg, italic = true },
      ['NeoTreeDotfile'] = { fg = theme.comment.fg, italic = true },
      ['NeoTreeHiddenByName'] = { fg = theme.comment.fg, italic = true },
      ['NeoTreeEndOfBuffer'] = { fg = theme.comment.fg },
      ['NeoTreeCursorLine'] = { bg = theme.cursorline_bg },
      ['NeoTreeGitStaged'] = { fg = theme.git_added_fg },
      ['NeoTreeGitUntracked'] = { fg = theme.git_untracked_fg },
      ['NeoTreeGitDeleted'] = { fg = theme.git_deleted_fg },
      ['NeoTreeGitModified'] = { fg = theme.git_modified_fg },
      ['NeoTreeSymbolicLinkTarget'] = { fg = custom.cyan },
      ['NeoTreeRootName'] = { fg = theme.fg, bold = true },
      ['NeoTreeTitleBar'] = { fg = custom.dark_gray, bg = theme.fg, bold = true },
    },
    barbar = {
      ['BufferCurrent'] = { fg = theme.fg, bg = theme.bg },
      ['BufferCurrentIndex'] = { fg = theme.fg, bg = theme.bg },
      ['BufferCurrentMod'] = { fg = custom.info, bg = theme.bg },
      ['BufferCurrentSign'] = { fg = custom.hint, bg = theme.bg },
      ['BufferCurrentTarget'] = { fg = custom.red, bg = theme.bg, bold = true },
      ['BufferVisible'] = { fg = theme.fg, bg = theme.bg },
      ['BufferVisibleIndex'] = { fg = theme.fg, bg = theme.bg },
      ['BufferVisibleMod'] = { fg = custom.info, bg = theme.bg },
      ['BufferVisibleSign'] = { fg = custom.gray, bg = theme.bg },
      ['BufferVisibleTarget'] = { fg = custom.red, bg = theme.bg, bold = true },
      ['BufferInactive'] = { fg = custom.gray, bg = custom.alt_bg },
      ['BufferInactiveIndex'] = { fg = custom.gray, bg = custom.alt_bg },
      ['BufferInactiveMod'] = { fg = custom.info, bg = custom.alt_bg },
      ['BufferInactiveSign'] = { fg = custom.gray, bg = custom.alt_bg },
      ['BufferInactiveTarget'] = { fg = custom.red, bg = custom.alt_bg, bold = true },
    },
    indent_blankline = {
      ['IndentBlanklineContextChar'] = { fg = theme.indent_guide_active_fg },
      ['IndentBlanklineContextStart'] = { sp = theme.indent_guide_active_fg, underline = true },
      ['IndentBlanklineChar'] = { fg = theme.indent_guide_fg },
    },
    cmp = {
      ['CmpItemAbbrMatch'] = { fg = theme.pmenu_item_sel_fg },
      ['CmpItemAbbrMatchFuzzy'] = { fg = theme.pmenu_item_sel_fg, italic = true },
      ['CmpItemAbbrDeprecated'] = { fg = custom.gray, strikethrough = true },
      ['CmpItemKindVariable'] = lsp_kinds['variable'],
      ['CmpItemKindModule'] = lsp_kinds['module'],
      ['CmpItemKindSnippet'] = lsp_kinds['snippet'],
      ['CmpItemKindFolder'] = lsp_kinds['folder'],
      ['CmpItemKindColor'] = lsp_kinds['color'],
      ['CmpItemKindFile'] = lsp_kinds['file'],
      ['CmpItemKindText'] = lsp_kinds['text'],
      ['CmpItemKindMethod'] = lsp_kinds['method'],
      ['CmpItemKindFunction'] = lsp_kinds['function'],
      ['CmpItemKindConstructor'] = lsp_kinds['constructor'],
      ['CmpItemKindField'] = lsp_kinds['field'],
      ['CmpItemKindProperty'] = lsp_kinds['property'],
      ['CmpItemKindUnit'] = lsp_kinds['unit'],
      ['CmpItemKindValue'] = lsp_kinds['value'],
      ['CmpItemKindEnum'] = lsp_kinds['enum'],
      ['CmpItemKindKeyword'] = lsp_kinds['keyword'],
      ['CmpItemKindReference'] = lsp_kinds['reference'],
      ['CmpItemKindConstant'] = lsp_kinds['constant'],
      ['CmpItemKindStruct'] = lsp_kinds['struct'],
      ['CmpItemKindEvent'] = lsp_kinds['event'],
      ['CmpItemKindOperator'] = lsp_kinds['operator'],
      ['CmpItemKindNamespace'] = lsp_kinds['namespace'],
      ['CmpItemKindPackage'] = lsp_kinds['package'],
      ['CmpItemKindString'] = lsp_kinds['string'],
      ['CmpItemKindNumber'] = lsp_kinds['number'],
      ['CmpItemKindBoolean'] = lsp_kinds['boolean'],
      ['CmpItemKindArray'] = lsp_kinds['array'],
      ['CmpItemKindObject'] = lsp_kinds['object'],
      ['CmpItemKindKey'] = lsp_kinds['key'],
      ['CmpItemKindNull'] = lsp_kinds['null'],
      ['CmpItemKindEnumMember'] = lsp_kinds['enumMember'],
      ['CmpItemKindClass'] = lsp_kinds['class'],
      ['CmpItemKindInterface'] = lsp_kinds['interface'],
      ['CmpItemKindTypeParameter'] = lsp_kinds['typeParameter'],
    },
    navic = {
      ['NavicIconsFile'] = lsp_kinds['file'],
      ['NavicIconsModule'] = lsp_kinds['module'],
      ['NavicIconsNamespace'] = lsp_kinds['namespace'],
      ['NavicIconsPackage'] = lsp_kinds['package'],
      ['NavicIconsClass'] = lsp_kinds['class'],
      ['NavicIconsMethod'] = lsp_kinds['method'],
      ['NavicIconsProperty'] = lsp_kinds['property'],
      ['NavicIconsField'] = lsp_kinds['field'],
      ['NavicIconsConstructor'] = lsp_kinds['constructor'],
      ['NavicIconsEnum'] = lsp_kinds['enum'],
      ['NavicIconsInterface'] = lsp_kinds['interface'],
      ['NavicIconsFunction'] = lsp_kinds['function'],
      ['NavicIconsVariable'] = lsp_kinds['variable'],
      ['NavicIconsConstant'] = lsp_kinds['constant'],
      ['NavicIconsString'] = lsp_kinds['string'],
      ['NavicIconsNumber'] = lsp_kinds['number'],
      ['NavicIconsBoolean'] = lsp_kinds['boolean'],
      ['NavicIconsArray'] = lsp_kinds['array'],
      ['NavicIconsObject'] = lsp_kinds['object'],
      ['NavicIconsKey'] = lsp_kinds['key'],
      ['NavicIconsKeyword'] = lsp_kinds['keyword'],
      ['NavicIconsNull'] = lsp_kinds['null'],
      ['NavicIconsEnumMember'] = lsp_kinds['enumMember'],
      ['NavicIconsStruct'] = lsp_kinds['struct'],
      ['NavicIconsEvent'] = lsp_kinds['event'],
      ['NavicIconsOperator'] = lsp_kinds['operator'],
      ['NavicIconsTypeParameter'] = lsp_kinds['typeParameter'],
      ['NavicText'] = { fg = theme.fg },
      ['NavicSeparator'] = { fg = theme.fg },
    },
    packer = {
      ['packerString'] = { fg = custom.gold },
      ['packerHash'] = { fg = custom.ui4_blue },
      ['packerOutput'] = { fg = custom.ui_purple },
      ['packerRelDate'] = { fg = custom.gray },
      ['packerSuccess'] = { fg = custom.success_green },
      ['packerStatusSuccess'] = { fg = custom.ui4_blue },
    },
    symbols_outline = {
      ['SymbolsOutlineConnector'] = { fg = custom.gray },
      ['FocusedSymbol'] = { bg = '#36383F' },
    },
    notify = {
      ['NotifyERRORBorder'] = { fg = '#8A1F1F' },
      ['NotifyWARNBorder'] = { fg = '#79491D' },
      ['NotifyINFOBorder'] = { fg = custom.ui_blue },
      ['NotifyDEBUGBorder'] = { fg = custom.gray },
      ['NotifyTRACEBorder'] = { fg = '#4F3552' },
      ['NotifyERRORIcon'] = { fg = custom.error },
      ['NotifyWARNIcon'] = { fg = custom.warn },
      ['NotifyINFOIcon'] = { fg = custom.ui4_blue },
      ['NotifyDEBUGIcon'] = { fg = custom.gray },
      ['NotifyTRACEIcon'] = { fg = custom.ui_purple },
      ['NotifyERRORTitle'] = { fg = custom.error },
      ['NotifyWARNTitle'] = { fg = custom.warn },
      ['NotifyINFOTitle'] = { fg = custom.ui4_blue },
      ['NotifyDEBUGTitle'] = { fg = custom.gray },
      ['NotifyTRACETitle'] = { fg = custom.ui_purple },
    },
    ts_rainbow = {
      -- ['TSRainbowRed'] = {},
      -- ['TSRainbowGreen'] = {},
      -- ['TSRainbowCyan'] = {},
      -- ['TSRainbowOrange'] = {},
      ['TSRainbowBlue'] = { fg = '#169FFF' },
      ['TSRainbowYellow'] = { fg = '#FFD602' },
      ['TSRainbowViolet'] = { fg = '#DA70D6' },
    },
    hop = {
      ['HopNextKey'] = { fg = '#4ae0ff' },
      ['HopNextKey1'] = { fg = '#d44eed' },
      ['HopNextKey2'] = { fg = '#b42ecd' },
      ['HopUnmatched'] = { fg = custom.gray },
      ['HopPreview'] = { fg = '#c7ba7d' },
    },
    crates = {
      ['CratesNvimLoading'] = { fg = custom.hint },
      ['CratesNvimVersion'] = { fg = custom.hint },
    },
  }
end

---Add in any enabled plugin's custom highlighting
---@param config horizon.Config
---@param plugins {[string]: horizon.Opts}
---@param highlights {[string]: horizon.Opts}
local function integrate_plugins(config, plugins, highlights)
  for plugin, enabled in pairs(config.plugins) do
    if enabled and plugins[plugin] then
      for key, value in pairs(plugins[plugin]) do
        highlights[key] = value
      end
    end
  end
  return highlights
end

---@param config horizon.Config
function M.set_highlights(config)
  local bg = vim.o.background
  local highlights = integrate_plugins(config, get_plugin_highlights(bg), get_highlights(bg))
  for name, value in pairs(highlights) do
    api.nvim_set_hl(0, name, value)
  end
end

return M
